<a href="https://colab.research.google.com/github/alaqsaka/university-related/blob/PrakDataMining/Tugas_Pert_5_Percobaan_ke_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
csv_path = '/content/hepatitis_praproses.csv'

In [2]:
df = pd.read_csv(csv_path)
df.head(50)

Unnamed: 0  Class       AGE  SEX  ...      SGOT   ALBUMIN   PROTIME  HISTOLOGY
0            0      2  0.323944    2  ...  0.006309  0.441860  0.618523          1
1            1      2  0.605634    1  ...  0.044164  0.325581  0.618523          1
2            2      2  1.000000    1  ...  0.028391  0.441860  0.618523          1
3            3      2  0.338028    1  ...  0.059937  0.441860  0.800000          1
4            4      2  0.380282    1  ...  0.293375  0.441860  0.618523          1
5            5      2  0.380282    1  ...  0.022082  0.441860  0.750000          1
6            6      1  0.619718    1  ...  0.113398  0.399364  0.618523          1
7            7      2  0.225352    1  ...  0.113398  0.399364  0.618523          1
8            8      2  0.450704    1  ...  0.053628  0.534884  0.618523          1
9            9      2  0.323944    1  ...  0.167192  0.418605  0.618523          1
10          10      2  0.450704    1  ...  0.025237  0.534884  0.850000          1
11          11      2  0.352113    1  ...  0.370662  0.372093  0.540000          1
12          12      2  0.478873    1  ...  0.072555  0.418605  0.520000          1
13          13      2  0.323944    1  ...  0.205047  0.651163  0.780000          1
14          14      2  0.563380    1  ...  0.072555  0.399364  0.618523          1
15          15      2  0.436620    1  ...  0.118297  0.186047  0.460000          1
16          16      2  0.830986    1  ...  0.061514  0.511628  0.618523          1
17          17      2  0.464789    1  ...  0.239748  0.441860  0.630000          1
18          18      2  0.436620    1  ...  0.044164  0.465116  0.850000          2
19          19      2  0.436620    1  ...  0.022082  0.488372  0.620000          1
20          20      2  0.211268    2  ...  0.009464  0.488372  0.640000          1
21          21      2  0.281690    1  ...  0.132492  0.465116  0.390000          1
22          22      2  0.338028    1  ...  0.009464  0.441860  1.000000          1
23          23      2  0.492958    1  ...  0.077287  0.604651  0.470000          1
24          24      2  0.253521    2  ...  0.006309  0.511628  0.700000          1
25          25      2  0.281690    1  ...  0.050473  0.395349  1.000000          1
26          26      2  0.591549    1  ...  0.053628  0.372093  0.618523          1
27          27      2  0.718310    2  ...  0.064669  0.139535  0.360000          1
28          28      2  0.760563    1  ...  0.017350  0.395349  1.000000          1
29          29      2  0.619718    1  ...  0.069401  0.581395  0.520000          1
30          30      1  0.450704    1  ...  0.132492  0.395349  0.400000          1
31          31      1  0.774648    1  ...  0.072555  0.399364  0.618523          1
32          32      2  0.478873    2  ...  0.061514  0.674419  0.740000          1
33          33      2  0.267606    2  ...  0.023659  0.395349  0.600000          1
34          34      2  0.394366    1  ...  0.123028  0.511628  0.730000          1
35          35      1  0.422535    1  ...  0.022082  0.488372  0.618523          1
36          36      2  0.225352    1  ...  0.214511  0.465116  0.900000          1
37          37      2  0.183099    2  ...  0.085174  0.418605  0.618523          1
38          38      2  0.492958    1  ...  0.000000  0.441860  1.000000          1
39          39      2  0.816901    1  ...  0.061514  0.186047  0.740000          2
40          40      2  0.633803    1  ...  0.064669  0.441860  0.210000          1
41          41      2  0.225352    1  ...  0.003155  0.581395  0.618523          1
42          42      2  0.366197    1  ...  0.119874  0.534884  0.600000          1
43          43      2  0.690141    1  ...  0.006309  0.534884  1.000000          1
44          44      2  0.380282    1  ...  0.113565  0.399364  0.618523          1
45          45      2  0.295775    1  ...  0.151420  0.534884  0.618523          1
46          46      2  0.422535    1  ...  0.104101  0.395349  0.618523          1
47          47      

In [3]:
df.drop('Unnamed: 0', inplace=True, axis=1)
# Menghapus kolom yang bukan kategorikal

del df['AGE']
del df['BILIRUBIN']
del df['ALK PHOSPHATE']
del df['SGOT']
del df['ALBUMIN']
del df['PROTIME']

df.head()

Class  SEX  STEROID  ANTIVIRALS  ...  SPIDERS  ASCITES  VARICES  HISTOLOGY
0      2    2        1           2  ...        2        2        2          1
1      2    1        1           2  ...        2        2        2          1
2      2    1        2           2  ...        2        2        2          1
3      2    1        2           1  ...        2        2        2          1
4      2    1        2           2  ...        2        2        2          1

[5 rows x 14 columns]

**Menentukan variabel independen dan variabel independen**

In [7]:
# Variabel independen 
x = df.drop(["Class"], axis = 1)
print("Variabel independen: ")
print(x.head())

# Variabel dependen 
y = df['Class']
print("Variabel dependen: ")
print(y.head())

Variabel independen: 
   SEX  STEROID  ANTIVIRALS  FATIGUE  ...  SPIDERS  ASCITES  VARICES  HISTOLOGY
0    2        1           2        2  ...        2        2        2          1
1    1        1           2        1  ...        2        2        2          1
2    1        2           2        1  ...        2        2        2          1
3    1        2           1        2  ...        2        2        2          1
4    1        2           2        2  ...        2        2        2          1

[5 rows x 13 columns]
Variabel dependen: 
0    2
1    2
2    2
3    2
4    2
Name: Class, dtype: int64


**Membagi dataset menjadi dua bagian: data testing (30%) dan data training (70%)**


In [19]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3,random_state=109) # 70% training and 30% test

In [29]:
X_train.shape

(108, 13)

In [30]:
y_train.shape

(108,)

In [31]:
X_test.shape

(47, 13)

In [32]:
y_test.shape

(47,)

**Membuat model latihan dengan menggunakan Multinomial Naive Bayes**

In [20]:
from sklearn.naive_bayes import MultinomialNB

#buat objek model Naive Bayes
model = MultinomialNB()

Selanjutnya, objek tersebut akan dilatih menggunakan data training. 
Memberikan fitur sebagai input latihan, kelas sebagai prediksinya.

In [34]:
#Latih dengan data
model_latih = model.fit(X_train, y_train)

In [36]:
# Menentukan hasil prediksi dari x_test
y_pred = model_latih.predict(X_test)
y_pred

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2])

In [38]:
import numpy as np
np.array(y_test)

array([2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 2,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2])

In [39]:
model_latih.predict_proba(X_test)

array([[0.11276729, 0.88723271],
       [0.11295384, 0.88704616],
       [0.29485675, 0.70514325],
       [0.16048601, 0.83951399],
       [0.12880767, 0.87119233],
       [0.24392148, 0.75607852],
       [0.12036133, 0.87963867],
       [0.1555213 , 0.8444787 ],
       [0.13571398, 0.86428602],
       [0.20444065, 0.79555935],
       [0.24556282, 0.75443718],
       [0.11276729, 0.88723271],
       [0.1737447 , 0.8262553 ],
       [0.16417756, 0.83582244],
       [0.2078907 , 0.7921093 ],
       [0.22549394, 0.77450606],
       [0.11276729, 0.88723271],
       [0.27414611, 0.72585389],
       [0.10350781, 0.89649219],
       [0.24544358, 0.75455642],
       [0.26695077, 0.73304923],
       [0.22300513, 0.77699487],
       [0.14379287, 0.85620713],
       [0.12491662, 0.87508338],
       [0.19286931, 0.80713069],
       [0.13257727, 0.86742273],
       [0.15303821, 0.84696179],
       [0.22300513, 0.77699487],
       [0.16317892, 0.83682108],
       [0.15323698, 0.84676302],
       [0.

In [40]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 0, 12],
       [ 0, 35]])

In [41]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           1       0.00      0.00      0.00        12
           2       0.74      1.00      0.85        35

    accuracy                           0.74        47
   macro avg       0.37      0.50      0.43        47
weighted avg       0.55      0.74      0.64        47



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [42]:
from sklearn.metrics import accuracy_score 
accuracy_score(y_test, y_pred)

0.7446808510638298